# 베이스 이미지를 도커 허브에서 가져온다.
FROM node:alpine

# 해당 애플리케이션이 위치하게 될 워크디렉토리
WORKDIR /app

# 소스 코드가 바뀔 때 마다 종속성 까지 다시 복사할 필요 없이 package.json 먼저 복사한다.
COPY package.json ./

# package.json 에 명시된 종속성을 다운받는다.
RUN npm install

# 소스 코드를 WORKDIR로 복사한다.
COPY ./ ./

# 컨테이너가 실행될때 실행할 명령어를 지정한다.
CMD ["npm", "run", "start"]